CREATE SEQUENCE IF NOT EXISTS maintenance_logs_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS members_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS staff_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS trainers_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE health_logs
(
    m_id       INTEGER                                   NOT NULL,
    time       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    heart_rate INTEGER,
    weight     INTEGER,
    CONSTRAINT health_logs_pkey PRIMARY KEY (m_id, time)
);

CREATE TABLE maintenance_logs
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    details     TEXT                                     NOT NULL,
    room_number INTEGER,
    status      TEXT                                     NOT NULL,
    s_id        INTEGER,
    CONSTRAINT maintenance_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE members
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name TEXT                                     NOT NULL,
    last_name  TEXT                                     NOT NULL,
    email      TEXT                                     NOT NULL,
    password   TEXT                                     NOT NULL,
    CONSTRAINT members_pkey PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    r_number INTEGER NOT NULL,
    CONSTRAINT rooms_pkey PRIMARY KEY (r_number)
);

CREATE TABLE staff
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name TEXT                                     NOT NULL,
    last_name  TEXT                                     NOT NULL,
    password   TEXT                                     NOT NULL,
    CONSTRAINT staff_pkey PRIMARY KEY (id)
);

CREATE TABLE trainers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name TEXT                                     NOT NULL,
    last_name  TEXT                                     NOT NULL,
    password   TEXT                                     NOT NULL,
    CONSTRAINT trainers_pkey PRIMARY KEY (id)
);

CREATE TABLE training_sessions
(
    t_id       INTEGER                NOT NULL,
    date       date                   NOT NULL,
    start_time time WITHOUT TIME ZONE NOT NULL,
    end_time   time WITHOUT TIME ZONE NOT NULL,
    m_id       INTEGER,
    room       INTEGER,
    CONSTRAINT training_sessions_pkey PRIMARY KEY (t_id, date, start_time)
);

CREATE TABLE unassigned_sessions
(
    t_id INTEGER                NOT NULL,
    date date                   NOT NULL,
    time time WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT unassigned_sessions_pkey PRIMARY KEY (t_id, date, time)
);

ALTER TABLE members
    ADD CONSTRAINT members_email_key UNIQUE (email);

ALTER TABLE health_logs
    ADD CONSTRAINT health_logs_m_id_fkey FOREIGN KEY (m_id) REFERENCES members (id) ON DELETE CASCADE;

ALTER TABLE maintenance_logs
    ADD CONSTRAINT maintenance_logs_room_number_fkey FOREIGN KEY (room_number) REFERENCES rooms (r_number) ON DELETE NO ACTION;

ALTER TABLE maintenance_logs
    ADD CONSTRAINT maintenance_logs_s_id_fkey FOREIGN KEY (s_id) REFERENCES staff (id) ON DELETE NO ACTION;

ALTER TABLE training_sessions
    ADD CONSTRAINT training_sessions_m_id_fkey FOREIGN KEY (m_id) REFERENCES members (id) ON DELETE SET NULL;

ALTER TABLE training_sessions
    ADD CONSTRAINT training_sessions_room_fkey FOREIGN KEY (room) REFERENCES rooms (r_number) ON DELETE SET NULL;

ALTER TABLE training_sessions
    ADD CONSTRAINT training_sessions_t_id_fkey FOREIGN KEY (t_id) REFERENCES trainers (id) ON DELETE CASCADE;

ALTER TABLE unassigned_sessions
    ADD CONSTRAINT unassigned_sessions_t_id_date_time_fkey FOREIGN KEY (t_id, date, time) REFERENCES training_sessions (t_id, date, start_time) ON DELETE NO ACTION;

CREATE VIEW user_summary AS
SELECT t.id,
       t.first_name,
       t.last_name,
       f.heart_rate AS latest_hr,
       f.weight     AS latest_w
FROM members t
         JOIN (SELECT h.m_id,
                      h.heart_rate,
                      h.weight,
                      m."time"
               FROM (SELECT health_logs.m_id,
                            max(health_logs."time") AS "time"
                     FROM health_logs
                     GROUP BY health_logs.m_id) m
                        JOIN health_logs h ON h.m_id = m.m_id AND m."time" = h."time") f ON t.id = f.m_id;

alter table user_summary
    owner to postgres;